### ISSUE TITLE
Support for SCION

### ISSUE THREAD

**Issue by lschulz** [seed-labs/seed-emulator#121]
[SCION](https://www.scion.org/scion) (Scalability, Control, and Isolation On Next-generation networks) is a new secure and reliable inter-domain routing protocol. SCION offers inter-domain path control with explicit trust by grouping ASes in Isolation Domains (ISDs) and embedding the cryptographically secured AS-level path into packet headers.

We at [NetSys Lab](https://github.com/netsys-lab) ([Otto-von-Guericke University](https://www.ovgu.de/en/)) are working on implementing support for SCION in the SEED emulator to run experiments comparing SCION and BGP routing in realistic Internet topologies. Currently we are developing a SCION layer similar to the existing eBGP layer [here](https://github.com/netsys-lab/seed-emulator/blob/lschulz/scion/seedemu/layers/Scion.py).

Since we would like to contribute our work back to the SEED emulator, we want to make sure to keep you informed on our work and keep it in line with the emulator's overall design.

Currently, the SCION layer API is designed to be used for example in a hybrid BGP and SCION network like this:
```python
from seedemu.core import Emulator
from seedemu.layers import Base, Ebgp, Routing, Scion, PeerRelationship
from seedemu.layers.Scion import LinkType as ScLinkType

# Initialize
emu = Emulator()
base = Base()
routing = Routing()
ebgp = Ebgp()
scion = Scion()

# SCION ISDs
scion.addIsd(1)

# Internet Exchange
base.createInternetExchange(100)

# AS-150
as150 = base.createAutonomousSystem(150)
as150.createNetwork('net0')
as150_router = as150.createRouter('br0')
as150_router.joinNetwork('net0').joinNetwork('ix100')
as150_router.crossConnect(153, 'br0', '10.50.0.2/29')
scion.setAsIsd(150, 1)
scion.setCoreAs(150, True)

# AS-151
as151 = base.createAutonomousSystem(151)
as151.createNetwork('net0')
as151.createRouter('br0').joinNetwork('net0').joinNetwork('ix100')
scion.setAsIsd(151, 1)
scion.setCoreAs(151, True)

# AS-152
as152 = base.createAutonomousSystem(152)
as152.createNetwork('net0')
as152.createRouter('br0').joinNetwork('net0').joinNetwork('ix100')
scion.setAsIsd(152, 1)
scion.setCoreAs(152, True)

# AS-153
as153 = base.createAutonomousSystem(153)
as153.createNetwork('net0')
as153_router = as153.createRouter('br0')
as153_router.joinNetwork('net0')
as153_router.crossConnect(150, 'br0', '10.50.0.3/29')
scion.setAsIsd(153, 1)
scion.setCertIssuer(153, 150)

# BGP Peering
ebgp.addPrivatePeering(100, 150, 151)
ebgp.addPrivatePeering(100, 151, 152)
ebgp.addPrivatePeering(100, 152, 150)
ebgp.addCrossConnectPeering(150, 153, PeerRelationship.Provider)

# SCION Peering
scion.addIxLink(100, 150, 151, ScLinkType.Core)
scion.addIxLink(100, 151, 152, ScLinkType.Core)
scion.addIxLink(100, 152, 150, ScLinkType.Core)
scion.addXcLink(150, 153, ScLinkType.Transit)
```

We can provide more examples once we have made more progress, but if you have any feedback already please let us know.

**Comment by wonkr** [comment]
We are glad to know that SCION team is willing to contribute our project. We have reviewed the Scion.py code in SCION's repository and found that it is well implemented. We could see the effort to follow the structure of the SEED Internet Emulator. It works really well and can generate the emulation files without any error. The design looks very practical and minimizes the change on the current system.


The `configure` part in `Scion layer` seems to comprises 4 steps as below.
1. _configure_links
: set the as router as scion router.
: get the config info(router node object, ip address)
2. _gen_scion_crypto
: generate pki cert files from the topology configured(configured links).
3. _install_scion
: install the necessary softwares to run scion protocol
4. _provision_router
: import cert and key file generated from _gen_scion_cyprto() to the each router node.


In your current design, you put the management of the link relations and software
installation in one single layer called Scion.py. I understand that your 
intention is to minimize the change on the existing Internet emulator, so
it is a reasonable design and very practical. 

In the long run, this design might cause trouble, because it does not align 
well with the current layered design of the emulator. It is better to put the 
functionality of SCION into different layers. We would like to propose another 
design for you to think about. This is just for your consideration, as your 
current design is acceptable.

SCION replaces the BGP protocol, which involves three layers in our current design: 
`Ebgp.py`, `Ibgp.py`, and `Routing.py`. 
The `Ebgp` and `Ibgp layers` only manage the relations, while the actual execution and
installation part is done in the `Routing` layer. In that respect, we propose 3
layers design for `SCION protocl` as below.

1. IntraScion.py - Manage the link relation inside an ISD.
2. InterScion.py - Manage the link relation between ISDs.
3. ScionRouting.py - Install and Run the necessary software.


The concepts of some of the components (like AS) have changed in SCION.
Instead of creating a separate class for them, we suggest using 
the sub-classes. For example, there is `_AutonomousSystem` class in
`Scion.py`. Instead of creating the class from the base, we can make it a
subclass of the current AutonomousSystem class.

```python
class ScionAutonomousSystem(AutonomousSystem):
...
```
It can be applied when implementing a ScionRouting.py as below.
```python
class ScionRouting(Routing):
...
```

In this way, we can make a change on the current code while still separating the 
SCION system from the current Internet Emulator structure.
 

Here is the example code based on the proposed design
```python
# Initialize
emu = Emulator()
# ScionBase is a subclass of Base class
# class ScionBase(Base)
scion_base = ScionBase()
# class ScionRouting(Routing)
scion_routing = ScionRouting()
ebgp = Ebgp()
intra_scion = IntraScion()

# Internet Exchange
scion_base.createInternetExchange(100)
# SCION ISDs
scoin_base.createIsolationDomain(1)

# AS-150
as150 = scion_base.createAutonomousSystem(150)
as150.createNetwork('net0')
as150_router = as150.createRouter('br0')
as150_router.joinNetwork('net0').joinNetwork('ix100')
as150_router.crossConnect(153, 'br0', '10.50.0.2/29')
as150.joinIsolationDomain(1, is_core=True)

# AS-151
as151 = scion_base.createAutonomousSystem(151)
as151.createNetwork('net0')
as151.createRouter('br0').joinNetwork('net0').joinNetwork('ix100')

# AS-152
as152 = scion_base.createAutonomousSystem(152)
as152.createNetwork('net0')
as152.createRouter('br0').joinNetwork('net0').joinNetwork('ix100')

# AS-153
as153 = scion_base.createAutonomousSystem(153)
as153.createNetwork('net0')
as153_router = as153.createRouter('br0')
as153_router.joinNetwork('net0')
as153_router.crossConnect(150, 'br0', '10.50.0.3/29')

# BGP Peering
ebgp.addPrivatePeering(100, 150, 151)
ebgp.addPrivatePeering(100, 151, 152)
ebgp.addPrivatePeering(100, 152, 150)
ebgp.addCrossConnectPeering(150, 153, PeerRelationship.Provider)

# SCION Peering
# similar to bgp api (Ebgp::addPrivatePeering)
intra_scion.setIsdAs(isd=1, asn=150, is_core=True)

# similar to bgp api (Ebgp::addPrivatePeerings)
intra_scion.setIsdAses(isd=1, core=[151, 152], none_core=[153])

intra_scion.addIxLink(100, 150, 151, ScLinkType.Core)
intra_scion.addIxLink(100, 151, 152, ScLinkType.Core)
intra_scion.addIxLink(100, 152, 150, ScLinkType.Core)

intra_scion.setCertIssuer(parent=150, child=153)
intra_scion.addXcLink(150, 153, ScLinkType.Transit)
```

Again, this new proposed design is only for you to consider. If you choose to continue
your current design, it is ok. In either way, we would be happy to test your 
implementation and provide timely feedback. Moreover, if 
changes are needed for the core to support SCION, we will consider that and implement it if
the needs are generic. 

We look forward to seeing the SCION protocol in action on the Internet Emulator soon.

**Comment by lschulz** [comment]
Thank you very much for the feedback. We have split the Scion layer into four new layers:
1. A `ScionBase` layer that inherits from `Base`
2. A `ScionRouting` Layer that inherits from `Routing`
3. A `ScionIsd` layer for managing the AS to ISD relationships
4. A `Scion` layer for managing the inter-AS links similar to `Ebgp`

We have some usage examples in `examples/scion`

I have created a pull request to make it easier to comment on the code: https://github.com/seed-labs/seed-emulator/pull/143
