### ISSUE TITLE
[Client] Animating packet flow not working

### ISSUE THREAD

**Issue by rleroi** [seed-labs/seed-emulator#164]
I'm running ping and set the filter to 'icmp', this does not show any animation like in this demo: https://www.youtube.com/watch?v=lfbO-eHt6qg&t=641s

I am also not sure that the logs are working correctly:
<img width="1121" alt="image" src="https://github.com/seed-labs/seed-emulator/assets/6817390/42137baf-4cbe-44e4-9f8f-8af040ad34cb">

I am on (ARM) Macbook M1 running the 'A00-simple-peering' example.

**Comment by wonkr** [comment]
This might occurs because of cpu compatibility issue. 
We are currently working on supporting full functions on ARM device at the `arm-support` branch. 
It is not merged yet as we are still working on running ethereum pow. 
You can test with `arm-support` branch. If it still does not solve the issue, please leave a comment here again. 
Thanks.

**Comment by wonkr** [comment]
I will close this issue as this is the same issue from ARM cpu which we are working on in this #159 issue.

**Comment by rleroi** [comment]
Thanks, it works now :)
