### ISSUE TITLE
"Error: fetching paths: no path available" in S02_scion_bgp_mixed

### ISSUE THREAD

**Issue by SonProCode** [seed-labs/seed-emulator#267]
Hello everyone, I am currently working on the example in section S02 according to the instructions in this link: https://github.com/seed-labs/seed-emulator/tree/master/examples/scion/S02_scion_bgp_mixed. 
I am encountering an issue in the section where SCION is not pinging, while the BGP part is working normally. Could anyone please help me identify what I might be doing wrong here? Thank you.
Here is my result when i ping:
![image](https://github.com/user-attachments/assets/03f3d5ab-bced-42eb-83ff-58283571f602)

**Comment by lschulz** [comment]
A recent update update to SCION (removal of the dispatcher) requires changes to the configuration of all SCION hosts. Using an old configuration with the new SCION binaries results in the SCION control service not starting and "no path found" errors.

The error should be fixed by #265 Could you try that branch?
