### ISSUE TITLE
Issues in Node.setFile API 

### ISSUE THREAD

**Issue by kevin-w-du** [seed-labs/seed-emulator#49]
I am trying to use Node.setFile() API to copy an executable file to container, but it seems this API can only handle strings, because the file copied into the container is different from the original file. We should support the binary option as well.

**Comment by magicnat** [comment]
A new API, `Node::importFile(hostpath, nodepath)`, where `hostpath` is the path of the file on the emulation host (should be an absolute path or can have problems otherwise; to use a relative path, consider obtaining the current path programmatically and create the absolute path.) and `nodepath` is the path of the file inside the node, is added in the latest commit to the `development` branch.

Note the file is only copied at render time (so if the emulation is dumped, the file will not be included).

**Comment by wonkr** [comment]
resolved.
